In [2]:
import sys
sys.path.append("../src")

In [3]:
import pandas as pd
import numpy as np
from encoders.ordinal import ProfilerOrdinalEncoder
from encoders.onehot import ProfilerOneHotEncoder
from profiler import DataProfiler

In [ ]:
import numpy as np
df_1 = pd.DataFrame({"status": ["ok", "fail", "warn", "other"]})
df_2 = pd.DataFrame({"status": [np.nan, "fail", "warn", "other"]})

In [ ]:
def check_encoder(df):
    encoder = ProfilerOrdinalEncoder(
        columns=["status"],
        categories=[["fail", "warn", "ok"]],
        handle_unknown="use_nan"
    )
    encoder.fit(df)
    df_encoded = encoder.transform(df)
    print(type(df_encoded))
    print(df_encoded)

In [ ]:
type(df_1)

In [ ]:
df_1

In [ ]:
check_encoder(df_1)

In [ ]:
df_2

In [ ]:
cenas = check_encoder(df_2)

In [ ]:
df_encoded

In [ ]:
df = df_1
encoder = ProfilerOrdinalEncoder(
        columns=["status"],
        categories=[["fail", "warn", "ok"]],
        handle_unknown="use_nan"
    )
encoder.fit(df)
df_encoded = encoder.transform(df)

In [ ]:
df_1

In [ ]:
df_encoded

In [ ]:
df_encoded = pd.DataFrame({"status": [0.0, 0, 0]})

In [ ]:
df_encoded

In [ ]:
df_decoded = encoder.inverse_transform(df_encoded)

In [ ]:
encoder.inverse_mappings

In [ ]:
df_decoded

In [ ]:
df_3 = pd.DataFrame({"Color": ["R", "B", "G", "B"]})

In [ ]:
df_3

In [ ]:
profile = DataProfiler(df_3)

In [ ]:
profile.print_report()

In [ ]:
encoder = ProfilerOneHotEncoder(profiler=profile, columns=["Color"])
encoder.fit(df_3)

In [ ]:
profile.print_report()

In [ ]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "Diana", "Eve"],
    "Gender": ["F", np.nan, "M", "F", "F"],
    "Age": [25, 30, 35, 28, 40],
    "Score": [85, 70, 90, 88, 76],
    "Status": ["Pass", "Fail", "Pass", "Pass", "Fail"]
})

## **OneHotEncoder: all OK**

In [3]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "Diana", "Eve"],
    "Gender": ["F", "F", "M", "F", "F"],
    "Age": [25, 30, 35, 28, 40],
    "Score": [85, 70, 90, 88, 76],
    "Status": ["Pass", "Fail", "Pass", "Pass", "Fail"]
})

In [4]:
profile = DataProfiler(df)
ohe = ProfilerOneHotEncoder(profiler=profile, columns=["Gender"])

In [5]:
profile.print_report()

n_samples: 5
n_features: 5
target: None
num_cols: ['Age', 'Score']
cat_cols: ['Name', 'Gender', 'Status']
mv_cols: []
mv_percentage: 0.0
duplicate_rows: 0
target_distribution: {}
continuous_cols: []
ordinal_cols: []
nominal_cols: []
binary_cols: []

In [6]:
ohe.fit(df)

ProfilerOneHotEncoder(columns=['Gender'],
                      profiler=<profiler.DataProfiler object at 0x132329d60>)

In [7]:
profile.print_report()

n_samples: 5
n_features: 5
target: None
num_cols: ['Age', 'Score']
cat_cols: ['Name', 'Gender', 'Status']
mv_cols: []
mv_percentage: 0.0
duplicate_rows: 0
target_distribution: {}
continuous_cols: []
ordinal_cols: []
nominal_cols: []
binary_cols: []
feature_mappings: {'Gender': ['F', 'M']}
inverse_mappings: {'Gender_F': ('Gender', 'F'), 'Gender_M': ('Gender', 'M')}

In [8]:
df_encoded = ohe.transform(df)

In [9]:
df_encoded

      Name  Age  Score Status  Gender_F  Gender_M
0    Alice   25     85   Pass         1         0
1      Bob   30     70   Fail         1         0
2  Charlie   35     90   Pass         0         1
3    Diana   28     88   Pass         1         0
4      Eve   40     76   Fail         1         0

In [10]:
df_decoded = ohe.inverse_transform(df_encoded)

In [11]:
df_decoded

      Name  Age  Score Status Gender
0    Alice   25     85   Pass      F
1      Bob   30     70   Fail      F
2  Charlie   35     90   Pass      M
3    Diana   28     88   Pass      F
4      Eve   40     76   Fail      F

In [12]:
df

      Name Gender  Age  Score Status
0    Alice      F   25     85   Pass
1      Bob      F   30     70   Fail
2  Charlie      M   35     90   Pass
3    Diana      F   28     88   Pass
4      Eve      F   40     76   Fail

In [13]:
ohe_binary = ProfilerOneHotEncoder(profiler=profile, drop="if_binary", columns=["Gender"])
df2 = ohe_binary.fit_transform(df)

In [14]:
df2

      Name  Age  Score Status  Gender_F
0    Alice   25     85   Pass         1
1      Bob   30     70   Fail         1
2  Charlie   35     90   Pass         0
3    Diana   28     88   Pass         1
4      Eve   40     76   Fail         1

In [15]:
df2_decoded = ohe_binary.inverse_transform(df2)

In [16]:
df2_decoded

      Name  Age  Score Status Gender
0    Alice   25     85   Pass      F
1      Bob   30     70   Fail      F
2  Charlie   35     90   Pass      M
3    Diana   28     88   Pass      F
4      Eve   40     76   Fail      F

In [17]:
ohe_all = ProfilerOneHotEncoder(profiler=profile, columns=["Gender", "Status"])
df3 = ohe_all.fit_transform(df)

In [18]:
df3

      Name  Age  Score  Gender_F  Gender_M  Status_Fail  Status_Pass
0    Alice   25     85         1         0            0            1
1      Bob   30     70         1         0            1            0
2  Charlie   35     90         0         1            0            1
3    Diana   28     88         1         0            0            1
4      Eve   40     76         1         0            1            0

In [19]:
df3_decoded = ohe_all.inverse_transform(df3)
df3_decoded

      Name  Age  Score Gender Status
0    Alice   25     85      F   Pass
1      Bob   30     70      F   Fail
2  Charlie   35     90      M   Pass
3    Diana   28     88      F   Pass
4      Eve   40     76      F   Fail

In [20]:
ohe_last = ProfilerOneHotEncoder(profiler=profile, drop="last", columns=["Gender", "Status"])
df4 = ohe_last.fit_transform(df)

In [21]:
df4

      Name  Age  Score  Gender_F  Status_Fail
0    Alice   25     85         1            0
1      Bob   30     70         1            1
2  Charlie   35     90         0            0
3    Diana   28     88         1            0
4      Eve   40     76         1            1

In [22]:
df4_decoded = ohe_last.inverse_transform(df4)
df4_decoded

      Name  Age  Score Gender Status
0    Alice   25     85      F   Pass
1      Bob   30     70      F   Fail
2  Charlie   35     90      M   Pass
3    Diana   28     88      F   Pass
4      Eve   40     76      F   Fail

## **OneHotEncoder: NaN in category**

In [23]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "Diana", "Eve"],
    "Gender": ["F", np.nan, "M", "F", "F"],
    "Age": [25, 30, 35, 28, 40],
    "Score": [85, 70, 90, 88, 76],
    "Status": ["Pass", "Fail", "Pass", "Pass", "Fail"]
})

In [24]:
profile = DataProfiler(df)
ohe = ProfilerOneHotEncoder(profiler=profile, columns=["Gender"])

In [25]:
profile.print_report()

n_samples: 5
n_features: 5
target: None
num_cols: ['Age', 'Score']
cat_cols: ['Name', 'Gender', 'Status']
mv_cols: ['Gender']
mv_percentage: 4.0
duplicate_rows: 0
target_distribution: {}
continuous_cols: []
ordinal_cols: []
nominal_cols: []
binary_cols: []

In [26]:
ohe.fit(df)

ProfilerOneHotEncoder(columns=['Gender'],
                      profiler=<profiler.DataProfiler object at 0x1324514f0>)

In [27]:
profile.print_report()

n_samples: 5
n_features: 5
target: None
num_cols: ['Age', 'Score']
cat_cols: ['Name', 'Gender', 'Status']
mv_cols: ['Gender']
mv_percentage: 4.0
duplicate_rows: 0
target_distribution: {}
continuous_cols: []
ordinal_cols: []
nominal_cols: []
binary_cols: []
feature_mappings: {'Gender': ['F', 'M']}
inverse_mappings: {'Gender_F': ('Gender', 'F'), 'Gender_M': ('Gender', 'M')}

In [28]:
df_encoded = ohe.transform(df)

In [29]:
df

      Name Gender  Age  Score Status
0    Alice      F   25     85   Pass
1      Bob    NaN   30     70   Fail
2  Charlie      M   35     90   Pass
3    Diana      F   28     88   Pass
4      Eve      F   40     76   Fail

In [30]:
df_encoded

      Name  Age  Score Status  Gender_F  Gender_M
0    Alice   25     85   Pass       1.0       0.0
1      Bob   30     70   Fail       NaN       NaN
2  Charlie   35     90   Pass       0.0       1.0
3    Diana   28     88   Pass       1.0       0.0
4      Eve   40     76   Fail       1.0       0.0

In [31]:
df_decoded = ohe.inverse_transform(df_encoded)

In [33]:
df_decoded

      Name  Age  Score Status Gender
0    Alice   25     85   Pass      F
1      Bob   30     70   Fail    NaN
2  Charlie   35     90   Pass      M
3    Diana   28     88   Pass      F
4      Eve   40     76   Fail      F

In [34]:
profile.print_report()

n_samples: 5
n_features: 5
target: None
num_cols: ['Age', 'Score']
cat_cols: ['Name', 'Gender', 'Status']
mv_cols: ['Gender']
mv_percentage: 4.0
duplicate_rows: 0
target_distribution: {}
continuous_cols: []
ordinal_cols: []
nominal_cols: []
binary_cols: []
feature_mappings: {'Gender': ['F', 'M']}
inverse_mappings: {'Gender_F': ('Gender', 'F'), 'Gender_M': ('Gender', 'M')}

In [35]:
ohe_binary = ProfilerOneHotEncoder(profiler=profile, drop="if_binary", columns=["Gender"])
df2 = ohe_binary.fit_transform(df)

In [36]:
df2

      Name  Age  Score Status  Gender_F
0    Alice   25     85   Pass       1.0
1      Bob   30     70   Fail       NaN
2  Charlie   35     90   Pass       0.0
3    Diana   28     88   Pass       1.0
4      Eve   40     76   Fail       1.0

In [38]:
df2_decoded = ohe_binary.inverse_transform(df2)
df2_decoded

      Name  Age  Score Status Gender
0    Alice   25     85   Pass      F
1      Bob   30     70   Fail    NaN
2  Charlie   35     90   Pass      M
3    Diana   28     88   Pass      F
4      Eve   40     76   Fail      F

## **OneHotEncoder: All same category**

In [39]:
df_ori = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "Diana", "Eve"],
    "Gender": ["F", "F", "F", "F", "F"],
    "Age": [25, 30, 35, 28, 40],
    "Score": [85, 70, 90, 88, 76],
    "Status": ["Pass", "Fail", "Pass", "Pass", "Fail"]
})

In [40]:
ohe = ProfilerOneHotEncoder(profiler=profile, columns=["Gender", "Status"])
df_encoded = ohe.fit_transform(df_ori)

In [41]:
df_encoded

      Name  Age  Score  Gender_F  Status_Fail  Status_Pass
0    Alice   25     85         1            0            1
1      Bob   30     70         1            1            0
2  Charlie   35     90         1            0            1
3    Diana   28     88         1            0            1
4      Eve   40     76         1            1            0

In [42]:
df_decoded = ohe.inverse_transform(df_encoded)
df_decoded

      Name  Age  Score Gender Status
0    Alice   25     85      F   Pass
1      Bob   30     70      F   Fail
2  Charlie   35     90      F   Pass
3    Diana   28     88      F   Pass
4      Eve   40     76      F   Fail

In [44]:
df_ori

      Name Gender  Age  Score Status
0    Alice      F   25     85   Pass
1      Bob      F   30     70   Fail
2  Charlie      F   35     90   Pass
3    Diana      F   28     88   Pass
4      Eve      F   40     76   Fail

## **OneHotEncoder: Unknown category on transform**

In [45]:
df_ori = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "Diana", "Eve"],
    "Gender": ["F", "M", "M", "F", "F"],
    "Age": [25, 30, 35, 28, 40],
    "Score": [85, 70, 90, 88, 76],
    "Status": ["Pass", "Fail", "Pass", "Pass", "Fail"]
})

In [46]:
df_ori

      Name Gender  Age  Score Status
0    Alice      F   25     85   Pass
1      Bob      M   30     70   Fail
2  Charlie      M   35     90   Pass
3    Diana      F   28     88   Pass
4      Eve      F   40     76   Fail

In [47]:
df_unk = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "Diana", "Eve"],
    "Gender": ["F", "BBB", "M", "F", "F"],
    "Age": [25, 30, 35, 28, 40],
    "Score": [85, 70, 90, 88, 76],
    "Status": ["Pass", "Fail", "KKKK", "Pass", "Fail"]
})

In [48]:
df_unk

      Name Gender  Age  Score Status
0    Alice      F   25     85   Pass
1      Bob    BBB   30     70   Fail
2  Charlie      M   35     90   KKKK
3    Diana      F   28     88   Pass
4      Eve      F   40     76   Fail

In [49]:
ohe = ProfilerOneHotEncoder(columns=["Gender", "Status"])
df_encoded_original = ohe.fit_transform(df_ori)

In [51]:
df_ori

      Name Gender  Age  Score Status
0    Alice      F   25     85   Pass
1      Bob      M   30     70   Fail
2  Charlie      M   35     90   Pass
3    Diana      F   28     88   Pass
4      Eve      F   40     76   Fail

In [50]:
df_encoded_original

      Name  Age  Score  Gender_F  Gender_M  Status_Fail  Status_Pass
0    Alice   25     85         1         0            0            1
1      Bob   30     70         0         1            1            0
2  Charlie   35     90         0         1            0            1
3    Diana   28     88         1         0            0            1
4      Eve   40     76         1         0            1            0

In [55]:
df_decoded_ori = ohe.inverse_transform(df_encoded_original)
df_decoded_ori

      Name  Age  Score Gender Status
0    Alice   25     85      F   Pass
1      Bob   30     70      M   Fail
2  Charlie   35     90      M   Pass
3    Diana   28     88      F   Pass
4      Eve   40     76      F   Fail

In [52]:
df_unk

      Name Gender  Age  Score Status
0    Alice      F   25     85   Pass
1      Bob    BBB   30     70   Fail
2  Charlie      M   35     90   KKKK
3    Diana      F   28     88   Pass
4      Eve      F   40     76   Fail

In [53]:
df_unk_encoded = ohe.transform(df_unk)

In [54]:
df_unk_encoded

      Name  Age  Score  Gender_F  Gender_M  Status_Fail  Status_Pass
0    Alice   25     85       1.0       0.0          0.0          1.0
1      Bob   30     70       NaN       NaN          1.0          0.0
2  Charlie   35     90       0.0       1.0          NaN          NaN
3    Diana   28     88       1.0       0.0          0.0          1.0
4      Eve   40     76       1.0       0.0          1.0          0.0

In [56]:
df_unk_decoded = ohe.inverse_transform(df_unk_encoded)
df_unk_decoded

      Name  Age  Score Gender Status
0    Alice   25     85      F   Pass
1      Bob   30     70    NaN   Fail
2  Charlie   35     90      M    NaN
3    Diana   28     88      F   Pass
4      Eve   40     76      F   Fail

## **Decoding OneHotEncoder (tests)**

In [ ]:
import pandas as pd
import numpy as np

X = pd.DataFrame({
    "OHE_A": [1, 0, 0],
    "OHE_B": [0, 1, 0]
})

def decode_row(row, ohe_list):
    for ohe_col, category in ohe_list:
        if ohe_col in row and row[ohe_col] == 1:
            return category
    return np.nan

ohe_list = [("OHE_A", "A"), ("OHE_B", "B")]

X["decoded"] = X.apply(decode_row, axis=1, args=(ohe_list,))
print(X)

- **What is row in `apply`?**
    - When we do `X.apply(decode_row, axis=1)`:
        - Each row is passed as a pandas Series
        - `row` is a Series where **index = column names** and **values = row values**
- **Why `if ohe_col in row` works:**
    - It checks if `ohe_col` (string name) is in the series

In [ ]:
X = pd.DataFrame({
    "OHE_A": [1, 0, 0],
    "OHE_B": [0, 1, 0]
})

In [ ]:
X

In [ ]:
ohe_cols = list(X.columns)
X.drop(columns=[col for col in ohe_cols if col in X.columns], inplace=True)
result = pd.DataFrame({
    "OHE_C": [1, 0, 0]})

X = pd.concat([X, result], axis=1)

In [ ]:
X

## **Using Encoders in ColumnTransformer**

In [1]:
import pandas as pd

df = pd.DataFrame({
    "Age": [25, 40, 32, 29, 50],                          # Numerical
    "Education": ["High School", "PhD", "Bachelors", "Masters", "Bachelors"],  # Ordinal
    "City": ["New York", "Paris", "Tokyo", "Paris", "Tokyo"]  # Nominal
})

df

   Age    Education      City
0   25  High School  New York
1   40          PhD     Paris
2   32    Bachelors     Tokyo
3   29      Masters     Paris
4   50    Bachelors     Tokyo

In [5]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import MinMaxScaler
from encoders.ordinal import ProfilerOrdinalEncoder
from encoders.onehot import ProfilerOneHotEncoder

In [6]:
num_features = ["Age"]
ordinal_features = ["Education"]
cat_features = ["City"]

In [9]:
preprocessor = ColumnTransformer([
    ("scale", MinMaxScaler(), num_features),
    ("encode_ordinal", ProfilerOrdinalEncoder(), ordinal_features),
    ("encode_one_hot", ProfilerOneHotEncoder(), num_features)
])

In [10]:
df_encoded = preprocessor.fit_transform(df)

In [11]:
df_encoded

array([[0.  , 1.  , 1.  , 0.  , 0.  , 0.  , 0.  ],
       [0.6 , 3.  , 0.  , 0.  , 0.  , 1.  , 0.  ],
       [0.28, 0.  , 0.  , 0.  , 1.  , 0.  , 0.  ],
       [0.16, 2.  , 0.  , 1.  , 0.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  , 0.  , 0.  , 0.  , 1.  ]])

## **Using Encoders in Pipelines**

In [12]:
from sklearn.pipeline import Pipeline

In [14]:
pipeline = Pipeline(steps=[
    ("preprocess", preprocessor)
])

In [15]:
pipeline.fit_transform(df)

array([[0.  , 1.  , 1.  , 0.  , 0.  , 0.  , 0.  ],
       [0.6 , 3.  , 0.  , 0.  , 0.  , 1.  , 0.  ],
       [0.28, 0.  , 0.  , 0.  , 1.  , 0.  , 0.  ],
       [0.16, 2.  , 0.  , 1.  , 0.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  , 0.  , 0.  , 0.  , 1.  ]])

### **Alternative**

In [19]:
df

   Age    Education      City
0   25  High School  New York
1   40          PhD     Paris
2   32    Bachelors     Tokyo
3   29      Masters     Paris
4   50    Bachelors     Tokyo

In [16]:
pipe = Pipeline(steps=[
    ("preprocess", ProfilerOrdinalEncoder(columns=["Education"], 
                                          categories=[["High School", "Bachelors", "Masters", "PhD"]]))
])

In [17]:
df_transformed = pipe.fit_transform(df)

In [18]:
df_transformed

   Age  Education      City
0   25          0  New York
1   40          3     Paris
2   32          1     Tokyo
3   29          2     Paris
4   50          1     Tokyo

### **Testing with the profile**

In [20]:
from profiler import DataProfiler

In [21]:
profile = DataProfiler(df)

In [23]:
profile.print_report()

n_samples: 5
n_features: 3
target: None
num_cols: ['Age']
cat_cols: ['Education', 'City']
mv_cols: []
mv_percentage: 0.0
duplicate_rows: 0
target_distribution: {}
continuous_cols: []
ordinal_cols: []
nominal_cols: []
binary_cols: []

In [24]:
pipe = Pipeline(steps=[
    ("preprocess", ProfilerOrdinalEncoder(profiler=profile,
                                          columns=["Education"], 
                                          categories=[["High School", "Bachelors", "Masters", "PhD"]]))
])

In [25]:
df_transformed = pipe.fit_transform(df)

In [26]:
df_transformed

   Age  Education      City
0   25          0  New York
1   40          3     Paris
2   32          1     Tokyo
3   29          2     Paris
4   50          1     Tokyo

In [27]:
profile.print_report()

n_samples: 5
n_features: 3
target: None
num_cols: ['Age']
cat_cols: ['Education', 'City']
mv_cols: []
mv_percentage: 0.0
duplicate_rows: 0
target_distribution: {}
continuous_cols: []
ordinal_cols: []
nominal_cols: []
binary_cols: []
feature_mappings: {'Education': {'High School': 0, 'Bachelors': 1, 'Masters': 2, 'PhD': 3}}
inverse_mappings: {'Education': {0: 'High School', 1: 'Bachelors', 2: 'Masters', 3: 'PhD'}}