In [1]:
import pandas as pd

df = pd.DataFrame({
    "Department": ["HR", "IT", "IT", "HR", "Sales", "Sales", "IT"],
    "Employee": ["Alice", "Bob", "Charlie", "Diana", "Eve", "Frank", "Grace"],
    "Salary": [50000, 60000, 65000, 52000, 70000, 72000, 58000],
    "Gender": ["F", "M", "M", "F", "F", "M", "F"]
})

In [2]:
df

  Department Employee  Salary Gender
0         HR    Alice   50000      F
1         IT      Bob   60000      M
2         IT  Charlie   65000      M
3         HR    Diana   52000      F
4      Sales      Eve   70000      F
5      Sales    Frank   72000      M
6         IT    Grace   58000      F

In [6]:
df.groupby("Department")["Employee"].count()

Department
HR       2
IT       3
Sales    2
Name: Employee, dtype: int64

In [8]:
df.groupby("Department").agg({
    "Salary": ["mean", "max", "min"],
    "Employee": "count"
})

             Salary               Employee
               mean    max    min    count
Department
HR          51000.0  52000  50000        2
IT          61000.0  65000  58000        3
Sales       71000.0  72000  70000        2

In [9]:
df.sort_values(by="Salary", ascending=False)

  Department Employee  Salary Gender
5      Sales    Frank   72000      M
4      Sales      Eve   70000      F
2         IT  Charlie   65000      M
1         IT      Bob   60000      M
6         IT    Grace   58000      F
3         HR    Diana   52000      F
0         HR    Alice   50000      F

In [10]:
df["DeptRank"] = df.groupby("Department")["Salary"].rank(ascending=False)

In [11]:
df

  Department Employee  Salary Gender  DeptRank
0         HR    Alice   50000      F       2.0
1         IT      Bob   60000      M       2.0
2         IT  Charlie   65000      M       1.0
3         HR    Diana   52000      F       1.0
4      Sales      Eve   70000      F       2.0
5      Sales    Frank   72000      M       1.0
6         IT    Grace   58000      F       3.0

In [14]:
df.pivot_table(
    values="Salary",
    index="Department",
    columns="Gender",
    aggfunc="mean"
)

Gender            F        M
Department
HR          51000.0      NaN
IT          58000.0  62500.0
Sales       70000.0  72000.0

In [ ]:
#Dummy pivot table

pd.pivot_table(
    data,               # our df
    values=None,        # values to aggregate (numeric or categorical for counts)
    index=None,         # what we want in rows, usually grouping keys  
    columns=None,       # what gets passed in columns
    aggfunc='mean',     # how to summarize the data: mean, sum, count, size, min, max
    fill_value=None,    # what to put in combinations that do not exist
    margins=False,      # if true, adds total (row and colum)
    dropna=True         # drops columns in output that are all NaN
)

In [12]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "class": ["NaN", "A", "B", "B", "C", "C"],
    "gender": ["F", "M", "F", "F", "M", "F"],
    "score": [90, None, 75, 85, 92, None]
})

In [13]:
df

  class gender  score
0   NaN      F   90.0
1     A      M    NaN
2     B      F   75.0
3     B      F   85.0
4     C      M   92.0
5     C      F    NaN

In [14]:
pd.pivot_table(
    df,
    index="class",
    columns="gender",
    values="score",
    aggfunc="count",
    #fill_value=0
)

gender    F    M
class
A       NaN  0.0
B       2.0  NaN
C       0.0  1.0
NaN     1.0  NaN

In [15]:
pd.pivot_table(
    df,
    index="class",
    columns="gender",
    aggfunc="size"
)

gender    F    M
class
A       NaN  1.0
B       2.0  NaN
C       1.0  1.0
NaN     1.0  NaN

- Use "count" → when you care about non-missing data in a specific column
- Use "size" → when you care about row frequency, regardless of missing data